#!/usr/bin/env bash

readonly ID_PREVIEW="preview"

[ ! -d "/tmp$PWD/" ] && mkdir -p "/tmp$PWD/"

previewclear() {
	declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
		> "$FIFO_UEBERZUG"
}

preview() {
	declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
	[x]="$2" [y]="$3" [width]="$4" [height]="$5" \
		 [path]="$PWD/$6") \
		 > "$FIFO_UEBERZUG"
}

main() {
	case "$1" in
	"clear")
		previewclear "$@"
		;;
	"draw")
		preview "$@"
		;;
	esac
}

main "$@"
