#!/bin/sh

[ -d "/tmp$PWD/" ] || mkdir -p "/tmp$PWD/"

preview_clear() {
	printf "action\tremove\tidentifier\tpreview\n" > "$UEBERZUG_FIFO"
}

preview_draw() {
	{
		printf 'action\tadd\tidentifier\tpreview\t'
		printf 'x\t%d\ty\t%d\t' "$2" "$3"
		printf 'width\t%d\theight\t%d\t' "$4" "$5"
		printf 'path\t%s\n' "$PWD/$6"
	} > "$UEBERZUG_FIFO"
}

preview_audio() {
	[ "$(command -v ffmpeg)" ] || {
		exit
	}

	[ -f "/tmp$PWD/$6.png" ] || \
		ffmpeg -i "$PWD/$6" "/tmp$PWD/$6.png" -y 2>/dev/null

	{
		printf 'action\tadd\tidentifier\tpreview\t'
		printf 'x\t%d\ty\t%d\t' "$2" "$3"
		printf 'width\t%d\theight\t%d\t' "$4" "$5"
		printf 'path\t%s\n' "/tmp$PWD/$6.png"
	} > "$UEBERZUG_FIFO"
}

preview_video() {
	[ "$(command -v ffmpegthumbnailer)" ] || {
		exit
	}

	[ -f "/tmp$PWD/$6.png" ] || \
		ffmpegthumbnailer -i "$PWD/$6" -o "/tmp$PWD/$6.png" -s 0 -q 10

	{
		printf 'action\tadd\tidentifier\tpreview\t'
		printf 'x\t%d\ty\t%d\t' "$2" "$3"
		printf 'width\t%d\theight\t%d\t' "$4" "$5"
		printf 'path\t%s\n' "/tmp$PWD/$6.png"
	} > "$UEBERZUG_FIFO"
}

preview_font() {
	[ "$(command -v fontpreview)" ] || {
		exit
	}

	[ -f "/tmp$PWD/$6.png" ] || \
		fontpreview -i "$PWD/$6" -o "/tmp$PWD/$6.png"

	{
		printf 'action\tadd\tidentifier\tpreview\t'
		printf 'x\t%d\ty\t%d\t' "$2" "$3"
		printf 'width\t%d\theight\t%d\t' "$4" "$5"
		printf 'path\t%s\n' "/tmp$PWD/$6.png"
	} > "$UEBERZUG_FIFO"
}

main() {
	case "$1" in
		clear) preview_clear "$@" ;;
		draw) preview_draw "$@" ;;
		audio) preview_audio "$@" ;;
		video) preview_video "$@" ;;
		font) preview_font "$@" ;;
	esac
}

main "$@"
